### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Luxian** [ikr/500px-slideshow#1]
Hi,

Wanted to try this on my secondary screen yesterday but doesn't work anymore (you don't have it hosted on you website anymore).

Any chance you can update it?

Thanks,

**Comment by ikr** [comment]
Ah, right. It didn't survive the migration to my new domain. I'll try to find some time to fix it this week.

**Comment by ikr** [comment]
New bookmarklet URL: http://ikr.su/h/500px-slideshow/bookmarklet.html
