### ISSUE TITLE
500px URL schema changed

### ISSUE THREAD

**Issue by rimonhanna** [ikr/500px-slideshow#2]
500px URL schema has changed causing the below line to generate wrong images URLs

thumbnailUrl.substr(0, thumbnailUrl.lastIndexOf("/")) + "/4.jpg"

I've been trying to figure out their new schema but I didn't get anywhere, could really use your help :)

Thanks

**Comment by ikr** [comment]
Sorry, I don't have time for this at the moment. I'd gladly accept a PR or even give the commit rights to someone who'd like to maintain the bookmarklet further.
